### ISSUE TITLE
toggle the disableGestures prop

### ISSUE THREAD

**Issue by eyaleizenberg** [Kureev/react-native-side-menu#104]
Is it possible to toggle the disableGestures prop? There are some scenes where I want it enabled and some where I want it disabled.

Thanks.

**Comment by alinz** [comment]
inside your component that you are using SideMenu, create a state and pass that state as an argument to `gestures` props. now every time you want to disable it just use `setState` and make that variable `false`. In this way you can control the gestures. 

```js
class MyComponent extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      gestures: true
    };
  }

  enableGesture(value) {
    this.setState({
      gestures: !!value
    });
  }

  render() {
    return(
      <SideMenu
        gestures={this.state.gestures}/>
    );
  }
}
```

instead of setState, you can use this.forceUpdate() inside the component that uses SideMenu to re-render the whole scene again.

```js
class MyComponent extends React.Component {
  constructor(props) {
    super(props);

    this.gestures = true
  }

  enableGesture(value) {
    this.gestures = !!value;
    this.forceUpdate();
  }

  render() {
    return(
      <SideMenu
        gestures={this.gestures}/>
    );
  }
}
```

Or use `Reflux` or `Redux` if you don't want to store state inside your component.

Cheers,

**Comment by Kureev** [comment]
Thanks a lot, @alinz!
