### ISSUE TITLE
Peer dependency issue with react native 0.6.0-rc

### ISSUE THREAD

**Issue by jshulk** [Kureev/react-native-side-menu#59]
Getting this unmet peer dependency error on installation. 
npm ERR! peerinvalid The package react-native does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-side-menu@0.9.0 wants react-native@>= 0.4

here's the package.json
{
  "name": "rn_hn",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "firebase": "2.2.6",
    "flux": "^2.0.3",
    "keymirror": "^0.1.1",
    "lodash": "3.9.3",
    "moment": "2.10.3",
    "object-assign": "^3.0.0",
    "q": "1.4.1",
    "react-native": "0.6.0-rc",
    "react-native-htmlview": "0.1.2",
    "url": "0.10.3"
  }
}

Does rc qualify as a version ? the ">=0.4" check seems to be failing which is odd, any ideas ?

**Comment by patrickomeara** [comment]
+1 Just hit this problem too.

**Comment by alinz** [comment]
I had the similar problem. What I did was fork `react-native` and change the `package.json` version to none `rc`. I'm already using my fork since I need `es6.modules`.

Other options is remove the `peerDependencies` in `package.json` of `react-native-side-menu`.

@Kureev, what do you think about this? Should we remove the `peerDependencies` and use the git tags similar to `react-native` version?

**Comment by Kureev** [comment]
We can change it to `*` or explicitly add `0.6.0-rc`.

**Comment by Kureev** [comment]
Should be fixed in `0.9.2`. I've added `0.5.0-rc1` and `0.6.0-rc` support
