### ISSUE TITLE
Cannot read property 'setNativeProps' of null

### ISSUE THREAD

**Issue by eyaleizenberg** [Kureev/react-native-side-menu#87]
Hi,
My main component either renders a login screen which doesn't have the side menu, or it renders the main screen which does have a side menu, depending on the states showMain or showLogin.

I allow 2 ways to open the side menu, either by dragging from the edge or using a button which triggers an event through flux to open it.

componentDidMount() {
    SideMenuStore.addOpenSideMenuListener(this.openSideMenu);
},

openSideMenu() {
    this.props.menuActions.open();
  },

This works fine. However, when I logout, and log back in, I can still open the side menu by draggin, but not with the button click. I receive the following error.

![screen shot 2015-08-17 at 11 54 58](https://cloud.githubusercontent.com/assets/1061345/9301404/d51d91ec-44d6-11e5-9674-61f895006f80.png)

Any clue why this is happening?

**Comment by Kureev** [comment]
@eyaleizenberg Which versions of react-native and react-native-side-menu you are using?

**Comment by eyaleizenberg** [comment]
RN = 0.8
Side menu = 0.9.5

**Comment by Kureev** [comment]
I think the problem is that component haven't been mounted to the DOM yet, when you invoke `openMenu` method. It tries to `updatePosition` which use `this.sideMenu`, but it seems that it's not there, because this property you get only after element rendered to the page (see https://github.com/Kureev/react-native-side-menu/blob/master/index.js#L248)

**Comment by eyaleizenberg** [comment]
That would mean that I couldn't drag it either, wouldn't it?

**Comment by Kureev** [comment]
Yeah, you're right. Seems that you have a leak so: when you log out, you destroy side-menu, and when you log in, you re-create it, but your flux implementation still have a link to old side-menu instance or something like this. Dragging works, because it's built-in in menu. Check the flux code, try to remove button handler when log out and re-assign it to the new instance after you log-in

**Comment by eyaleizenberg** [comment]
@Kureev I can't find it. Any chance we can have a quick skype call to try and find the issue?

**Comment by Kureev** [comment]
Probably after 19:00 CEST. Or you can share a code, I'll try to take a look

**Comment by eyaleizenberg** [comment]
It looks like none of my components are removing the listeners.

In my Menu component I have:

  componentWillUnmount() {
    SideMenuStore.removeOpenSideMenuListener(() => { console.log("aaa"); });
  },

And the SideMenuStore

var SideMenuStore = _.assign({}, EventEmitter.prototype, {
  emitChange() {
    this.emit(OPEN_SIDE_MENU_EVENT);
  },

  addOpenSideMenuListener(callback) {
    this.on(OPEN_SIDE_MENU_EVENT, callback);
  },

  removeOpenSideMenuListener(callback) {
    this.removeListener(OPEN_SIDE_MENU_EVENT, callback);
  }
});

The removeOpenSideMenuListener is called but the callback never happens. Any clue?

**Comment by eyaleizenberg** [comment]
OK, I figured it out. Turns out the callback function that you pass to removeListener has to be the same one you passed to "on".

I'm new to Flux... Sorry for the long post.

Thanks anyway.
P.S - This component is great!

**Comment by Kureev** [comment]
Thanks for the warm words! No problems, I'm here to help! Let me know if you'll need any other help with component
